### ISSUE TITLE
Source code of "libaudioclassifier.so"

### ISSUE THREAD

**Issue by hillolsarker** [denzilferreira/com.aware.plugin.studentlife.audio_final#8]
I am considering to include additional features in the voice feature vector. Here is the signature that I found in "AudioManager":
```
private native void features(short[] audio, float[] voicingFeatures,
                                 float[] observationProbability, byte[] inferenceResults,
                                 int[] numbeOfPeaks, float[] autoCorrelationPeaks,
                                 short[] autoCorrelationPeakLags);

```
Would it be feasible to open source the shared library "libaudioclassifier.so"?

**Comment by denzilferreira** [comment]
Unfortunately, this is owned by Cornell and Dartmouth. I do not have the source of the library.
